let categoryId = 1;
let productId = 101;

export const categories = [
  {
    id: categoryId++,
    name: "Beer",
    logo: { img: "/BeerPhotos/spacedust.png" },
    products: [
      {
        id: productId++,
        name: "Lagunitas IPA",
        img: "/BeerPhotos/lagunitas.png",
        description: "IPA",
        category: "Beer",
        alcoholPercentage: 6.2,
        country: "USA",
        tags: ["IPA"],
      },
      {
        id: productId++,
        name: "Space Dust IPA",
        img: "/BeerPhotos/spacedust.png",
        description: "IPA",
        category: "Beer",
        alcoholPercentage: 8.2,
        country: "USA",
        tags: ["IPA"],
      },
      {
        id: productId++,
        name: "Cass 6-pack",
        img: "/BeerPhotos/cass6pack.webp",
        description: "Korean Beer",
        category: "Beer",
        alcoholPercentage: 4.5,
        country: "South Korea",
        tags: [],
      },
    ],
  },
  {
    id: categoryId,
    name: "Cocktails",
    logo: { img: "/CocktailPhotos/moscowmule.png" },
    products: [
      {
        id: productId++,
        name: "Michelada",
        img: "/CocktailPhotos/michelada.png",
        description: "Michelada",
        category: "Cocktail",
        alcoholPercentage: 4.5,
        country: "Mexico",
        tags: ["Cocktail"],
      },
      {
        id: productId++,
        name: "Espresso Martini",
        img: "/CocktailPhotos/espressomartini.webp",
        description: "Espresso Martini",
        category: "Cocktail",
        alcoholPercentage: 24,
        country: "England",
        tags: ["Cocktail"],
      },
      {
        id: productId++,
        name: "Moscow Mule",
        img: "/CocktailPhotos/moscowmule.png",
        description: "Moscow Mule",
        category: "Cocktail",
        alcoholPercentage: 11,
        country: "USA",
        tags: ["Cocktail"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Cognac",
    logo: { img: "/CognacPhotos/hennesy.png" },
    products: [
      {
        id: productId++,
        name: "Hennesy",
        img: "/CognacPhotos/hennesy.png",
        description: "Hennesy",
        category: "Cognac",
        alcoholPercentage: 40,
        country: "France",
        tags: ["Cognac"],
      },
      {
        id: productId++,
        name: "Remy Martin 1738",
        img: "/CognacPhotos/remymartin.png",
        description: "Remy Martin 1738",
        category: "Cognac",
        alcoholPercentage: 40,
        country: "France",
        tags: ["Cognac"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Tequila",
    logo: { img: "/TequilaPhotos/donjulio1942.webp" },
    products: [
      {
        id: productId++,
        name: "Don Julio 1942",
        img: "/TequilaPhotos/donjulio1942.webp",
        description: "Don Julio 1942",
        category: "Tequila",
        alcoholPercentage: 40,
        country: "Mexico",
        tags: ["Tequila"],
      },
      {
        id: productId++,
        name: "Don Julio Anejo",
        img: "/TequilaPhotos/djanejo.png",
        description: "Don Julio Anejo",
        category: "Tequila",
        alcoholPercentage: 40,
        country: "Mexico",
        tags: ["Tequila"],
      },
      {
        id: productId++,
        name: "Patron",
        img: "/TequilaPhotos/patron.png",
        description: "Patron",
        category: "Tequila",
        alcoholPercentage: 40,
        country: "Mexico",
        tags: ["Tequila"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Vodka",
    logo: { img: "/VodkaPhotos/greygoose.png" },
    products: [
      {
        id: productId++,
        name: "Grey Goose",
        img: "/VodkaPhotos/greygoose.png",
        description: "Grey Goose",
        category: "Vodka",
        alcoholPercentage: 40,
        country: "France",
        tags: ["Vodka"],
      },
      {
        id: productId++,
        name: "Titos",
        img: "/VodkaPhotos/titos.png",
        description: "Titos",
        category: "Vodka",
        alcoholPercentage: 40,
        country: "USA",
        tags: ["Vodka"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Whiskey",
    logo: { img: "/WhiskeyPhotos/macallan.png" },
    products: [
      {
        id: productId++,
        name: "Macallan",
        img: "/WhiskeyPhotos/macallan.png",
        description: "Whiskey",
        category: "Whiskey",
        alcoholPercentage: 58,
        country: "Scotland",
        tags: ["Whiskey"],
      },
      {
        id: productId++,
        name: "Wild Turkey",
        img: "/WhiskeyPhotos/wildturkey.webp",
        description: "Whiskey",
        category: "Whiskey",
        alcoholPercentage: 53,
        country: "USA",
        tags: ["Whiskey"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Wine",
    logo: { img: "/WinePhotos/lafleur.png" },
    products: [
      {
        id: productId++,
        name: "Chateau Lafleur 2003, Pomerol",
        img: "/WinePhotos/lafleur.png",
        description: "Chateau Lafleur 2003, Pomerol",
        category: "",
        alcoholPercentage: 13.5,
        country: "France",
        tags: ["Wine"],
      },
    ],
  },
];
