let categoryId = 1;
let productId = 101;

export const categories = [
  {
    id: categoryId++,
    name: "Coffee",
    logo: { img: "/CoffeePhotos/bluebottle.png" },
    products: [
      {
        id: productId++,
        name: "Blue Bottle Coffee",
        img: "/CoffeePhotos/bluebottle.png",
        description: "Louisianna Coffee",
        category: "Coffee",
        caffeine: 6.2,
        country: "USA",
        tags: ["Coffee"],
      },
      {
        id: productId++,
        name: "Starbucks Frappuccino Vanilla",
        img: "/CoffeePhotos/sbvanilla.png",
        description: "Coffee",
        category: "Vanilla Coffee",
        caffeine: 8.2,
        country: "USA",
        tags: ["Coffee"],
      },
      {
        id: productId++,
        name: "Starbucks Frappuccino White Chocolate",
        img: "/CoffeePhotos/sbwhite.png",
        description: "White Chocolate Coffee",
        category: "Coffee",
        caffeine: 4.5,
        country: "USA",
        tags: [],
      },
    ],
  },
  {
    id: categoryId,
    name: "Dairy",
    logo: { img: "/DairyPhotos/chobanistrawberry.png" },
    products: [
      {
        id: productId++,
        name: "Chobani Strawberries & Cream Greek Yogurt Drink",
        img: "/DairyPhotos/chobanistrawberry.png",
        description: "Chobani Strawberries & Cream Greek Yogurt Drink",
        category: "Dairy",
        caffeine: 4.5,
        country: "Mexico",
        tags: ["Dairy"],
      },
      {
        id: productId++,
        name: "Chobani Mixed Berries Greek Yogurt Drink",
        img: "/DairyPhotos/chobaniberry.png",
        description: "Chobani Mixed Berries Greek Yogurt Drink",
        category: "Dairy",
        caffeine: 24,
        country: "USA",
        tags: ["Dairy"],
      },
      {
        id: productId++,
        name: "Fairlife 2% Ultra Filtered Milk",
        img: "/DairyPhotos/fairlifereducedfat.png",
        description: "Fairlife 2% Ultra Filtered Milk",
        category: "Dairy",
        caffeine: 11,
        country: "USA",
        tags: ["Dairy"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Juice",
    logo: { img: "/JuicePhotos/applejuice.png" },
    products: [
      {
        id: productId++,
        name: "Mott's Apple Juice",
        img: "/JuicePhotos/applejuice.png",
        description: "Mott's Apple Juice",
        category: "Juice",
        caffeine: 40,
        country: "USA",
        tags: ["Juice"],
      },
      {
        id: productId++,
        name: "Simply Orange Juice",
        img: "/JuicePhotos/oj.png",
        description: "Simply Orange Juice",
        category: "Juice",
        caffeine: 40,
        country: "USA",
        tags: ["Juice"],
      },
      {
        id: productId++,
        name: "Snapple Kiwi Strawberry",
        img: "/JuicePhotos/snapplekiwi.png",
        description: "Kiwi Strawberry Juice",
        category: "Juice",
        caffeine: 40,
        country: "USA",
        tags: ["Juice"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Energy Drinks",
    logo: { img: "/EnergyDrinkPhotos/redbull.png" },
    products: [
      {
        id: productId++,
        name: "Monster Energy Drink",
        img: "/EnergyDrinkPhotos/monster.png",
        description: "Monster Energy Drink",
        category: "Energy Drink",
        caffeine: 16,
        country: "USA",
        tags: ["Energy Drink"],
      },
      {
        id: productId++,
        name: "Monster Energy Drink Zero Sugar",
        img: "/EnergyDrinkPhotos/monsterzero.png",
        description: "Monster Energy Drink Zero Sugar",
        category: "Energy Drink",
        caffeine: 16,
        country: "USA",
        tags: ["Energy Drink", "Sugar Free"],
      },
      {
        id: productId++,
        name: "Red Bull Energy Drink",
        img: "/EnergyDrinkPhotos/redbull.png",
        description: "Red Bull Energy Drink",
        category: "Energy Drink",
        caffeine: 16,
        country: "USA",
        tags: ["Energy Drink"],
      },
      {
        id: productId++,
        name: "Red Bull Energy Drink Zero Sugar",
        img: "/EnergyDrinkPhotos/redbullzero.png",
        description: "Red Bull Energy Drink Zero Sugar",
        category: "Energy Drink",
        caffeine: 16,
        country: "USA",
        tags: ["Energy Drink", "Zero Sugar"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Sodas",
    logo: { img: "/SodaPhotos/coke.png" },
    products: [
      {
        id: productId++,
        name: "Coca-Cola",
        img: "/SodaPhotos/coke.png",
        description: "Coca-Cola Soda",
        category: "Soda",
        caffeine: 40,
        country: "USA",
        tags: ["Soda"],
      },
      {
        id: productId++,
        name: "Diet Coke",
        img: "/SodaPhotos/dietcoke.png",
        description: "Diet Coke Soda",
        category: "Soda",
        caffeine: 40,
        country: "USA",
        tags: ["Soda", "Sugar Free"],
      },
      {
        id: productId++,
        name: "Dr Pepper Strawberries & Cream Zero Sugar",
        img: "/SodaPhotos/drpepperstrawzero.png",
        description: "Dr Pepper Strawberries & Cream Zero Sugar Soda",
        category: "Soda",
        caffeine: 40,
        country: "USA",
        tags: ["Soda", "Sugar Free"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Water",
    logo: { img: "/WaterPhotos/icelandic.png" },
    products: [
      {
        id: productId++,
        name: "Icelandic Natural Spring Water",
        img: "/WaterPhotos/icelandic.png",
        description: "Icelandic Natural Spring Water",
        category: "Water",
        caffeine: 40,
        country: "Iceland",
        tags: ["Water"],
      },
      {
        id: productId++,
        name: "Fiji Water",
        img: "/WaterPhotos/fiji.png",
        description: "Fiji Water",
        category: "Water",
        caffeine: 40,
        country: "Fiji",
        tags: ["Water"],
      },
      {
        id: productId++,
        name: "San Pellegrino Sparkling Water",
        img: "/WaterPhotos/spellegrino.png",
        description: "San Pellegrino Sparkling Water",
        category: "Water",
        caffeine: 40,
        country: "Italy",
        tags: ["Water"],
      },
    ],
  },
  {
    id: categoryId,
    name: "Tea",
    logo: { img: "/TeaPhotos/azgreentea.png" },
    products: [
      {
        id: productId++,
        name: "Arizona Green Tea",
        img: "/TeaPhotos/azgreentea.png",
        description: "Arizona Green Tea",
        category: "Tea",
        caffeine: 58,
        country: "USA",
        tags: ["Tea"],
      },
      {
        id: productId++,
        name: "Ito En Unsweetend Green Tea",
        img: "/TeaPhotos/greentea.png",
        description: "Ito En Unsweetend Green Tea",
        category: "Tea",
        caffeine: 53,
        country: "Japan",
        tags: ["Tea"],
      },
      {
        id: productId++,
        name: "Snapple Peach Tea",
        img: "/TeaPhotos/snapplepeach.png",
        description: "Peach Tea",
        category: "Tea",
        caffeine: 40,
        country: "USA",
        tags: ["Tea"],
      },
      {
        id: productId++,
        name: "Snapple Peach Tea Zero Sugar",
        img: "/TeaPhotos/snapplepeachzero.png",
        description: "Peach Tea Tea Zero Sugar",
        category: "Tea",
        caffeine: 40,
        country: "USA",
        tags: ["Tea", "Sugar Free"],
      },
    ],
  },
];
