export const categories = [
  {
    id: 1,
    name: "Beer",
    logo: { img: "/BeerPhotos/spacedust.png" },
    products: [
      {
        id: 101,
        name: "Lagunitas IPA",
        img: "/BeerPhotos/lagunitas.png",
        description: "IPA",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
      {
        id: 102,
        name: "Space Dust IPA",
        img: "/BeerPhotos/spacedust.png",
        description: "IPA",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
      {
        id: 103,
        name: "Cass 6-pack",
        img: "/BeerPhotos/cass6pack.webp",
        description: "Korean Beer",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
    ],
  },
  {
    id: 2,
    name: "Wine",
    logo: { img: "/WinePhotos/lafleur.png" },
    products: [
      {
        id: 201,
        name: "Chateau Lafleur 2003, Pomerol",
        img: "/WinePhotos/lafleur.png",
        description: "Chateau Lafleur 2003, Pomerol",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
    ],
  },
  {
    id: 3,
    name: "Cocktails",
    logo: { img: "/CocktailPhotos/moscowmule.png" },
    products: [
      {
        id: 301,
        name: "Michelada",
        img: "/CocktailPhotos/michelada.png",
        description: "Michelada",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
      {
        id: 302,
        name: "Espresso Martini",
        img: "/CocktailPhotos/espressomartini.webp",
        description: "Espresso Martini",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
      {
        id: 303,
        name: "Moscow Mule",
        img: "/CocktailPhotos/moscowmule.png",
        description: "Moscow Mule",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
    ],
  },
  {
    id: 4,
    name: "Cognac",
    logo: { img: "/CognacPhotos/hennesy.png" },
    products: [
      {
        id: 1,
        name: "Hennesy",
        img: "/CognacPhotos/hennesy.png",
        description: "Hennesy",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
      {
        id: 2,
        name: "Remy Martin 1738",
        img: "/CognacPhotos/remymartin.png",
        description: "Remy Martin 1738",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
    ],
  },
  {
    id: 5,
    name: "Tequila",
    logo: { img: "/TequilaPhotos/donjulio1942.webp" },
    products: [
      {
        id: 501,
        name: "Don Julio 1942",
        img: "/TequilaPhotos/donjulio1942.webp",
        description: "Don Julio 1942",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
      {
        id: 502,
        name: "Don Julio Anejo",
        img: "/TequilaPhotos/djanejo.png",
        description: "Don Julio Anejo",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
      {
        id: 503,
        name: "Patron",
        img: "/TequilaPhotos/patron.png",
        description: "Patron",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
    ],
  },
  {
    id: 6,
    name: "Vodka",
    logo: { img: "/VodkaPhotos/greygoose.png" },
    products: [
      {
        id: 601,
        name: "Grey Goose",
        img: "/VodkaPhotos/greygoose.png",
        description: "Grey Goose",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
      {
        id: 602,
        name: "Titos",
        img: "/VodkaPhotos/titos.png",
        description: "Titos",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
    ],
  },
  {
    id: 7,
    name: "Whiskey",
    logo: { img: "/WhiskeyPhotos/macallan.png" },
    products: [
      {
        id: 701,
        name: "Macallan",
        img: "/WhiskeyPhotos/macallan.png",
        description: "Whiskey",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
      {
        id: 702,
        name: "Wild Turkey",
        img: "/WhiskeyPhotos/wildturkey.webp",
        description: "Whiskey",
        category:"",
        alcoholPercentage:"",
        country:"",
        tags: [],
      },
    ],
  },
];
